[mcp_servers.linear]
command = "npx"
args = ["-y", "mcp-remote", "https://mcp.linear.app/sse"]

[mcp_servers.context7]
command = "npx"
args = ["-y", "@upstash/context7-mcp"]

[mcp_servers.grep]
command = "npx"
args = ["-y", "mcp-remote", "https://mcp.grep.app"]

[mcp_servers.notionMCP]
command = "npx"
args = ["-y", "mcp-remote", "https://mcp.notion.com/mcp"]

[mcp_servers.markitdown-mcp]
command = "uvx"
args = ["markitdown-mcp"]

[mcp_servers.deepwiki]
command = "npx"
args = ["-y", "mcp-remote", "https://mcp.deepwiki.com/sse"]

